#!/bin/bash

# Copyright (c) 2015 Jim Fuller  
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0
  
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DEPIFY_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

CURRENTDIR=`pwd`

#default values
#####################################################################
COMMAND=$1 
PACKAGE=$2
VERSION=$3
VERSION=${VERSION:-latest}
INITREPO=$4
APP_DIR=$CURRENTDIR
LIB_DIR=/lib/
#####################################################################

while getopts 'c:p:v:a::l:h' OPTION
do
case $OPTION in
    c) COMMAND="$OPTARG";;
    p) PACKAGE="$OPTARG";;
    v) VERSION="$OPTARG";;
    r) INITREPO="$OPTARG";;
    a) APP_DIR="$OPTARG";;
    a) LIB_DIR="$OPTARG";;
    *)
      usage
      exit 1;
  esac
done

if [[ $# -eq 0 ]] ; then
    COMMAND="usage"
    PACKAGE=""
    VERSION=""
fi

if [ "$1" == "help" ]; then
    COMMAND="usage"
    PACKAGE=""
    VERSION=""
fi

# create lib directory if it does not exist
if [ ! -d ".$LIB_DIR" ]; then
mkdir .$LIB_DIR
fi

# create empty depify.xml if it does not exist (run depify init)
if  [ ! -e "$CURRENTDIR/.depify.xml" ]; then
    # run xproc pipeline
    echo '<depify xmlns="https://github.com/xquery/depify"/>' > $CURRENTDIR/.depify.xml    
fi
# run xproc pipeline
echo -e `java  -cp "$DEPIFY_DIR/resolver.properties" -jar $DEPIFY_DIR/deps/xmlcalabash/calabash.jar --config  $DEPIFY_DIR/xmlcalabash.xml --saxon-configuration $DEPIFY_DIR/saxon.xml -isource=$CURRENTDIR/.depify.xml -oresult=- -Xtransparent-json $DEPIFY_DIR/libs/xproc/depify.xpl command="$COMMAND" package="$PACKAGE" version=$VERSION init-repo-uri="$INITREPO" app_dir=$APP_DIR app_dir_lib=$LIB_DIR`
